-- ==========================================
-- SyncTeam Supabase Schema
-- ==========================================

-- 1. PROFILES
-- Extends the default auth.users table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text default 'Member', -- 'Admin', 'Member', 'Viewer'
  avatar_url text,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Profiles are viewable by everyone in the org (authenticated)
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone" on public.profiles
  for select using (auth.role() = 'authenticated');
create policy "Users can insert their own profile" on public.profiles
  for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', coalesce(new.raw_user_meta_data->>'role', 'Member'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. CLIENTS
create table public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  company text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.clients enable row level security;
create policy "Authenticated users can view clients" on public.clients for select using (auth.role() = 'authenticated');
create policy "Admins/Members can create clients" on public.clients for insert with check (auth.role() = 'authenticated');
create policy "Admins/Members can update clients" on public.clients for update using (auth.role() = 'authenticated');
create policy "Admins can delete clients" on public.clients for delete using (auth.role() = 'authenticated');


-- 3. PROJECTS
create table public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  client_id bigint references public.clients(id) on delete set null,
  client_name text,
  description text,
  start_date date,
  end_date date,
  budget numeric,
  status text default 'Active',
  progress integer default 0,
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.projects enable row level security;
create policy "Authenticated users can view projects" on public.projects for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert projects" on public.projects for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update projects" on public.projects for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete projects" on public.projects for delete using (auth.role() = 'authenticated');


-- 4. TASKS
create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  project_id bigint references public.projects(id) on delete cascade,
  assignee_id uuid references public.profiles(id),
  assignee_name text,
  status text default 'Pending',
  priority text default 'Medium',
  due_date date,
  time_spent integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tasks enable row level security;
create policy "Authenticated users can view tasks" on public.tasks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert tasks" on public.tasks for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update tasks" on public.tasks for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete tasks" on public.tasks for delete using (auth.role() = 'authenticated');

-- 5. SUBTASKS
create table public.subtasks (
  id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(id) on delete cascade,
  title text not null,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.subtasks enable row level security;
create policy "Authenticated users can view subtasks" on public.subtasks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can modify subtasks" on public.subtasks for all using (auth.role() = 'authenticated');


-- 6. ACTIVITY LOGS
create table public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  user_name text,
  action text not null,
  entity_type text not null,
  entity_name text,
  entity_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.activity_logs enable row level security;
create policy "Everyone can view logs" on public.activity_logs for select using (auth.role() = 'authenticated');
create policy "Users can insert logs" on public.activity_logs for insert with check (auth.role() = 'authenticated');
