/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'syncUpdates': MotiaStream<{ id: string; type: 'TASK_CREATED' | 'TASK_UPDATED' | 'USER_LOGGED_IN'; data: unknown; timestamp: string }>
  }

  interface Handlers {
    'ListUsers': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'HelloWorld': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}